/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#ifndef UNISTRING_CONFIG_H
#define UNISTRING_CONFIG_H

#include "../config.h"

#endif /* UNISTRING_CONFIG_H */
#define amemxfrm libunistring_amemxfrm
#define c_strcasecmp libunistring_c_strcasecmp
#define c_strncasecmp libunistring_c_strncasecmp
#define freea libunistring_freea
#define fseterr libunistring_fseterr
#define gl_locale_name libunistring_gl_locale_name
#define gl_locale_name_default libunistring_gl_locale_name_default
#define gl_locale_name_environ libunistring_gl_locale_name_environ
#define gl_locale_name_posix libunistring_gl_locale_name_posix
#define gl_locale_name_thread libunistring_gl_locale_name_thread
#define gl_unicase_special_lookup libunistring_gl_unicase_special_lookup
#define gl_uninorm_compose_lookup libunistring_gl_uninorm_compose_lookup
#define gl_uninorm_decomp_chars_table libunistring_gl_uninorm_decomp_chars_table
#define gl_uninorm_decomp_index_table libunistring_gl_uninorm_decomp_index_table
#define gl_uninorm_decompose_merge_sort_fromto libunistring_gl_uninorm_decompose_merge_sort_fromto
#define gl_uninorm_decompose_merge_sort_inplace libunistring_gl_uninorm_decompose_merge_sort_inplace
#define glthread_once_singlethreaded libunistring_glthread_once_singlethreaded
#define glthread_recursive_lock_init_multithreaded libunistring_glthread_recursive_lock_init_multithreaded
#define hard_locale libunistring_hard_locale
#define iconveh_close libunistring_iconveh_close
#define iconveh_open libunistring_iconveh_open
#define is_basic_table libunistring_is_basic_table
#define mbsnlen libunistring_mbsnlen
#define mem_cd_iconveh libunistring_mem_cd_iconveh
#define mem_iconveh libunistring_mem_iconveh
#define mem_iconveha libunistring_mem_iconveha
#define memcmp2 libunistring_memcmp2
#define mmalloca libunistring_mmalloca
#define printf_frexp libunistring_printf_frexp
#define printf_frexpl libunistring_printf_frexpl
#define rpl_isnanf libunistring_rpl_isnanf
#define rpl_isnanl libunistring_rpl_isnanl
#define rpl_strstr libunistring_rpl_strstr
#define rpl_wcwidth libunistring_rpl_wcwidth
#define str_cd_iconveh libunistring_str_cd_iconveh
#define str_iconveh libunistring_str_iconveh
#define str_iconveha libunistring_str_iconveha
#define u16_casemap libunistring_u16_casemap
#define u16_is_invariant libunistring_u16_is_invariant
#define u16_printf_parse libunistring_u16_printf_parse
#define u32_casemap libunistring_u32_casemap
#define u32_is_invariant libunistring_u32_is_invariant
#define u32_printf_parse libunistring_u32_printf_parse
#define u8_casemap libunistring_u8_casemap
#define u8_is_invariant libunistring_u8_is_invariant
#define u8_printf_parse libunistring_u8_printf_parse
#define u_printf_fetchargs libunistring_u_printf_fetchargs
#define uc_bidi_class_lookup libunistring_uc_bidi_class_lookup
#define uc_combining_class_lookup libunistring_uc_combining_class_lookup
#define uc_compat_decomposition libunistring_uc_compat_decomposition
#define uc_general_category_lookup libunistring_uc_general_category_lookup
#define uc_is_case_ignorable libunistring_uc_is_case_ignorable
#define uc_is_cased libunistring_uc_is_cased
#define uc_joining_group_lookup libunistring_uc_joining_group_lookup
#define uc_joining_type_lookup libunistring_uc_joining_type_lookup
#define uc_locale_languages_lookup libunistring_uc_locale_languages_lookup
#define uc_property_lookup libunistring_uc_property_lookup
#define uc_script_lookup libunistring_uc_script_lookup
#define uc_tocasefold libunistring_uc_tocasefold
#define ulc_printf_parse libunistring_ulc_printf_parse
#define uniconv_register_autodetect libunistring_uniconv_register_autodetect
#define unilbrk_is_all_ascii libunistring_unilbrk_is_all_ascii
#define unilbrk_is_utf8_encoding libunistring_unilbrk_is_utf8_encoding
#define unilbrk_table libunistring_unilbrk_table
#define unilbrkprop libunistring_unilbrkprop
#define uniwbrk_table libunistring_uniwbrk_table
